version: '3.9'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: mysql
        container_name: platinium-tech-task-database
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_ADMIN_USER: ${MYSQL_ADMIN_USER}
            MYSQL_ADMIN_PASS: ${MYSQL_ADMIN_PASS}
            MYSQL_WEB_USER: ${MYSQL_WEB_USER}
            MYSQL_WEB_PASS: ${MYSQL_WEB_PASS}
            MYSQL_DATABASE: platinium_tickets
            TZ: UTC
        volumes:
            - dbdata:/var/lib/mysql
            - ./etc/mysql/init-scripts/:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
    ###< doctrine/doctrine-bundle ###
    php:
        build:
            context: .
            dockerfile: etc/php/Dockerfile
        container_name: platinium-tech-task-php
        ports:
            - "9000"
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - ./:/var/www/html
            - ./logs/app:/var/www/html/var/log
        environment:
            DATABASE_URL: "mysql://${MYSQL_WEB_USER}:${MYSQL_WEB_PASS}@database:3306/platinium_tickets?serverVersion=5.7"
            MIGRATIONS_DATABASE_URL: "mysql://${MYSQL_ADMIN_USER}:${MYSQL_ADMIN_PASS}@database:3306/platinium_tickets?serverVersion=5.7"
            TEST_DATABASE_URL: "mysql://${MYSQL_ADMIN_USER}:${MYSQL_ADMIN_PASS}@database:3306/platinium_tickets_test?serverVersion=5.7"
            MAILER_DSN: "smtp://platinium-tech-task-mailhog:1025?auth_mode=login"
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            APP_ENV: ${APP_ENV}
            REDIS_USER: ${REDIS_USER}
            REDIS_PASS: ${REDIS_PASS}
    nginx:
        image: nginx
        container_name: platinium-tech-task-nginx
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./etc/nginx/templates:/etc/nginx/templates
            - ./logs/nginx:/var/log/nginx
        ports:
            - "${NGINX_HTTP_PORT}:80"
    redis:
        image: redis/redis-stack-server
        container_name: platinium-tech-task-redis
        healthcheck:
            test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        environment:
            REDIS_ARGS: "--requirepass ${REDIS_ROOT_PASS} --user ${REDIS_USER} on >${REDIS_PASS} ~* allcommands --user default off nopass nocommands"
        volumes:
            - ./redis-data/:/data
        ports:
            - "${REDIS_PORT}:6379"
    mailhog:
        image: ${MAILHOG_IMAGE:-mailhog/mailhog}
        container_name: platinium-tech-task-mailhog
        environment:
            MH_MAILDIR_PATH: /data
            MH_STORAGE: maildir
        volumes:
            - mailhog_data:/data:rw
        ports:
            - "${MAILHOG_SMTP_PORT}:1025"
            - "${MAILHOG_WEB_PORT}:8025"

volumes:
    dbdata:
    mailhog_data: